export const products = [
    // Mobile Category
    {
      id: "k1jg1i0j-bgdg-6i1g-ebhd-f2g8h1hib1b1",
      category: "Mobile",
      name: "Asus ROG Phone 5",
      stock: "in stock",
      brand: "Asus",
      ratings: 4.8,
      reviews: 1600,
      original_price: 79999,
      discount_price: 72999,
      description: "Asus ROG Phone 5 with Snapdragon 888, 144Hz AMOLED display, and 6000mAh battery for gaming.",
      images: [
        { img: "https://m.media-amazon.com/images/I/61snq2WdB6L._AC_UY327_FMwebp_QL65_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61UgUaFCurL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71SOAcLZpSL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71HOPa+IxtL._SX679_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
    {
      id: "l2kh2j1k-chgh-7j2h-fcif-g3h9i2ijc2c2",
      category: "Mobile",
      name: "Motorola Edge 20 Pro",
      stock: "in stock",
      brand: "Motorola",
      ratings: 4.5,
      reviews: 1100,
      original_price: 69999,
      discount_price: 64999,
      description: "Motorola Edge 20 Pro with 6.7-inch OLED display, Snapdragon 870, and 108MP triple camera.",
      images: [
        { img: "https://m.media-amazon.com/images/I/41AyFY4MhHL._SX300_SY300_QL70_FMwebp_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81Zriuo9BiL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/816VYFgJGsL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71O-rL-pdQL._SX679_.jpg" },
      ],
      best_seller: false,
      new_product: false,
    },
    {
      id: "m3li3k2l-dhih-8k3i-gdji-h4i0j3jkd3d3",
      category: "Mobile",
      name: "Nokia X20",
      stock: "out of stock",
      brand: "Nokia",
      ratings: 3.5,
      reviews: 900,
      original_price: 49999,
      discount_price: 43999,
      description: "Nokia X20 with 6.67-inch Full HD+ display, Snapdragon 480 5G, and 64MP quad camera.",
      images: [
        { img: "https://m.media-amazon.com/images/I/7166xlyA4zL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71iBVTX580L._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51keb7hhtyL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71y4ym+-peL._SX679_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
    {
      id: "n4mj4l3m-ejji-9l4j-hfkj-i5j1k4kle4e4",
      category: "Mobile",
      name: "Huawei P40 Pro",
      stock: "in stock",
      brand: "Huawei",
      ratings: 5,
      reviews: 1400,
      original_price: 79999,
      discount_price: 74999,
      description: "Huawei P40 Pro with Kirin 990 5G, 6.58-inch OLED display, and 50MP Ultra Vision Leica camera.",
      images: [
        { img: "https://m.media-amazon.com/images/I/617B9vlv+XL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/41ahW+KKYQL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61+veocvnGL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/512iL18-2PL._SX679_.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
    {
      id: "o5nk5m4n-fkkj-0m5k-iglk-j6k2l5lmf5f5",
      category: "Mobile",
      name: "Sony Xperia 1 III",
      stock: "in stock",
      brand: "Sony",
      ratings: 4.7,
      reviews: 1000,
      original_price: 99999,
      discount_price: 89999,
      description: "Sony Xperia 1 III with 6.5-inch 4K HDR OLED display, Snapdragon 888, and 12MP triple camera.",
      images: [
        { img: "https://m.media-amazon.com/images/I/61g1pqSjAhL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61tRqUl4hyL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51BWdKswXFL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51TQf+x0tcL._SX679_.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
  
    // Electronics Category
    {
      id: "p1pi2o3p-ckok-1l2k-hbbi-j7k8l9mno9p9",
      category: "Electronics",
      name: "Sony WH-1000XM4",
      stock: "in stock",
      brand: "Sony",
      ratings: 4.9,
      reviews: 2500,
      original_price: 29999,
      discount_price: 26999,
      description: "Sony WH-1000XM4 wireless noise-canceling headphones with 30-hour battery life and touch controls.",
      images: [
        { img: "https://m.media-amazon.com/images/I/51eAkzYNjrL._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61x20TUXDQS._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51HnzvVdHbL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61rCUQp+pDL._SY679_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
    {
      id: "q2pj3o4q-dpop-2m3j-icli-k8l9m0nop0q0",
      category: "Electronics",
      name: "Bose QuietComfort 35 II",
      stock: "in stock",
      brand: "Bose",
      ratings: 4.8,
      reviews: 2200,
      original_price: 28999,
      discount_price: 25999,
      description: "Bose QuietComfort 35 II with Alexa voice control and world-class noise cancellation.",
      images: [
        { img: "https://m.media-amazon.com/images/I/51RE0DBn5VL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51r1LweTgaL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61IXNgBNPOL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51fXq5ybbQL._SX450_.jpg" },
      ],
      best_seller: true,
      new_product: true,
    },
    {
      id: "r3kq4p5r-efrf-3n4k-jdjd-m9n0o1pqr1r1",
      category: "Electronics",
      name: "Apple AirPods Pro",
      stock: "in stock",
      brand: "Apple",
      ratings: 4.7,
      reviews: 1900,
      original_price: 24999,
      discount_price: 22999,
      description: "Apple AirPods Pro with active noise cancellation and customizable fit.",
      images: [
        { img: "https://m.media-amazon.com/images/I/61SUj2aKoEL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61sRKTAfrhL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51emillNpWL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/51+vJkbGtJL._SX679_.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
    {
      id: "s4lr5q6s-fsfs-4o5l-kdjd-l0m1n2pqr2s2",
      category: "Electronics",
      name: "Samsung Galaxy Buds Pro",
      stock: "in stock",
      brand: "Samsung",
      ratings: 4.6,
      reviews: 1700,
      original_price: 19999,
      discount_price: 17999,
      description: "Samsung Galaxy Buds Pro with active noise canceling and immersive sound.",
      images: [
        { img: "https://m.media-amazon.com/images/I/61KVX-MbIUL._SX450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61lEskbCaoL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81EcW9I7uDL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81ZnkXiV6EL._SY450_.jpg" },
      ],
      best_seller: true,
      new_product: true,
    },
  
    // Gaming Category
    {
      id: "t5rm6u7t-gggg-5p6j-kcjc-n1o2p3qrs3t3",
      category: "Gaming",
      name: "Havic HV G-92 Gamepad",
      stock: "in stock",
      brand: "Havit",
      ratings: 4.6,
      reviews: 180,
      original_price: 5999,
      discount_price: 3999,
      description: "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
      images: [
        { img: "https://m.media-amazon.com/images/I/41uWz7F2x0L._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/41q+S8aBtzL._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/41lRu2UI6CL._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61voGK8OuyL._SX466_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
    {
      id: "u6sn7v8u-hhii-6q7k-ldlf-o2p3q4rst4u4",
      category: "Gaming",
      name: "Logitech G Pro X Superlight",
      stock: "in stock",
      brand: "Logitech",
      ratings: 4.9,
      reviews: 2100,
      original_price: 15999,
      discount_price: 13999,
      description: "Logitech G Pro X Superlight wireless gaming mouse with HERO sensor and lightweight design.",
      images: [
        { img: "https://m.media-amazon.com/images/I/41PLZjfVlzL._SX300_SY300_QL70_FMwebp_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81bSJ5LC2DL._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71g322X8gTL._SX466_.jpg" },
        { img: "https://m.media-amazon.com/images/I/714NubDvR8L._SX466_.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
    {
      id: "v7to8w9v-iiij-7r8l-meme-p3q4r5stu5v5",
      category: "Gaming",
      name: "Razer BlackWidow V3",
      stock: "in stock",
      brand: "Razer",
      ratings: 4.7,
      reviews: 1500,
      original_price: 12999,
      discount_price: 10999,
      description: "Razer BlackWidow V3 mechanical gaming keyboard with Chroma RGB lighting and tactile switches.",
      images: [
        { img: "https://m.media-amazon.com/images/I/6124OpB-LRL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61OjTmn08ZL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71o55M0YlRL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71IkjP74ALL._SY450_.jpg" },
      ],
      best_seller: true,
      new_product: true,
    },
    {
      id: "w8ux9y0w-jjkk-8s9k-nfnd-q4r5s6tuv6w6",
      category: "Gaming",
      name: "Corsair Virtuoso RGB Wireless",
      stock: "in stock",
      brand: "Corsair",
      ratings: 4.8,
      reviews: 1300,
      original_price: 17999,
      discount_price: 14999,
      description: "Corsair Virtuoso RGB Wireless gaming headset with 7.1 surround sound and high-fidelity audio.",
      images: [
        { img: "https://m.media-amazon.com/images/I/619w5E8UpbL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/610-4gS5wFL._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61oor5N69+L._SY450_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61AAFvFxjjL._SY450_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
  
    // Home Appliances Category
    {
      id: "x9vz0a1x-kkjk-9t0p-mgfh-r5s6t7uvw7x7",
      category: "Home Appliances",
      name: "Dyson V11 Absolute",
      stock: "in stock",
      brand: "Dyson",
      ratings: 4.9,
      reviews: 3000,
      original_price: 54999,
      discount_price: 49999,
      description: "Dyson V11 Absolute cordless vacuum cleaner with powerful suction and intelligent cleaning modes.",
      images: [
        { img: "https://m.media-amazon.com/images/I/418vSp+SqzL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71qBUHlI2rL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61Nn2Q0BL5S._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/41UlCeExUHL.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
    {
      id: "y1az2b3y-llml-0p1r-hhfh-s6t7u8vwx8y8",
      category: "Home Appliances",
      name: "Philips Airfryer XXL",
      stock: "in stock",
      brand: "Philips",
      ratings: 4.8,
      reviews: 2700,
      original_price: 12999,
      discount_price: 9999,
      description: "Philips Airfryer XXL with Fat Removal Technology for healthier cooking with less oil.",
      images: [
        { img: "https://m.media-amazon.com/images/I/61hidViNSDL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/713ZAuuFw4L._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/61OnibyrXOL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71+dtvoWbiL._SX679_.jpg" },
      ],
      best_seller: true,
      new_product: true,
    },
    {
      id: "z2ba3c4z-mmnm-1q2s-gggh-t7u8v9wxy9z9",
      category: "Home Appliances",
      name: "Samsung 7kg Front Load Washing Machine",
      stock: "in stock",
      brand: "Samsung",
      ratings: 4.6,
      reviews: 1900,
      original_price: 34999,
      discount_price: 29999,
      description: "Samsung 7kg front load washing machine with EcoBubble technology and digital inverter motor.",
      images: [
        { img: "https://m.media-amazon.com/images/I/413bVo8q2iL._SY445_SX342_QL70_FMwebp_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81thQOGBpfL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81wnChc5wRL._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71hZHnFI4DL._SX679_.jpg" },
      ],
      best_seller: false,
      new_product: true,
    },
    {
      id: "a3zb4c5a-oonm-3r4t-nbkj-u8v9w0xy0z0z",
      category: "Home Appliances",
      name: "LG Side-by-Side Refrigerator",
      stock: "in stock",
      brand: "LG",
      ratings: 4.7,
      reviews: 2100,
      original_price: 74999,
      discount_price: 69999,
      description: "LG side-by-side refrigerator with smart inverter compressor and multi-air flow system.",
      images: [
        { img: "https://m.media-amazon.com/images/I/312xwgU0CGL._SY445_SX342_QL70_FMwebp_.jpg" },
        { img: "https://m.media-amazon.com/images/I/71NMpiH+o1L._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/715j80GR87L._SX679_.jpg" },
        { img: "https://m.media-amazon.com/images/I/81XRv7334hL._SX679_.jpg" },
      ],
      best_seller: true,
      new_product: false,
    },
     // Computers Category
  {
    id: "d4b6f7c8-e9d0-4f8e-b0ab-c1d2e3f4g5h6",
    category: "Computers",
    name: "Dell XPS 13",
    stock: "in stock",
    brand: "Dell",
    ratings: 4.8,
    reviews: 1200,
    original_price: 119999,
    discount_price: 109999,
    description: "Dell XPS 13 laptop with Intel Core i7, 16GB RAM, and 512GB SSD.",
    images: [
      { img: "https://m.media-amazon.com/images/I/51zY-mOR7kL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61YvpeFp6ZL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/51ZnWtK4oPL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/610y1Bnxa4L._SX679_.jpg" },
    ],
    best_seller: true,
    new_product: false,
  },
  {
    id: "e5f6g7h8-i9j0-5k6l-m7n8-o9p0q1r2s3t4",
    category: "Computers",
    name: "Apple MacBook Pro 16",
    stock: "in stock",
    brand: "Apple",
    ratings: 4.9,
    reviews: 1500,
    original_price: 239999,
    discount_price: 219999,
    description: "Apple MacBook Pro 16 with M1 Pro chip, 32GB RAM, and 1TB SSD.",
    images: [
      { img: "https://m.media-amazon.com/images/I/316ArzLeJ2L._SY445_SX342_QL70_FMwebp_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71-6roO29AL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61ChHwbxObL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61uNK7su24L._SX679_.jpg" },
    ],
    best_seller: true,
    new_product: true,
  },
  {
    id: "f7g8h9i0-j1k2-6l7m-n8o9-p0q1r2s3t4u5",
    category: "Computers",
    name: "HP Envy x360",
    stock: "in stock",
    brand: "HP",
    ratings: 4.7,
    reviews: 900,
    original_price: 84999,
    discount_price: 79999,
    description: "HP Envy x360 convertible laptop with AMD Ryzen 5, 8GB RAM, and 256GB SSD.",
    images: [
      { img: "https://m.media-amazon.com/images/I/71pN9Lk355L._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81ZmI8bJmxL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81r18BeZyKL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81uUlN4blXL._SX679_.jpg" },
    ],
    best_seller: false,
    new_product: false,
  },

  // Fashion Category
  {
    id: "g8h9i0j1-k2l3-4m5n-o6p7-q8r9s0t1u2v3",
    category: "Fashion",
    name: "Nike Air Max 270",
    stock: "in stock",
    brand: "Nike",
    ratings: 4.8,
    reviews: 2500,
    original_price: 12999,
    discount_price: 10999,
    description: "Nike Air Max 270 sneakers with a sleek design and comfortable cushioning.",
    images: [
      { img: "https://m.media-amazon.com/images/I/51QV2hTjbJL._SY675_.jpg" },
      { img: "https://m.media-amazon.com/images/I/51UcgCzuwPL._SY575_.jpg" },
      { img: "https://m.media-amazon.com/images/I/518zmYxmLUL._SY675_.jpg" },
      { img: "https://m.media-amazon.com/images/I/51InoOSeJZL._SY675_.jpg" },
    ],
    best_seller: true,
    new_product: true,
  },
  {
    id: "h9i0j1k2-l3m4-5n6o-p7q8-r9s0t1u2v3w4",
    category: "Fashion",
    name: "Adidas Ultraboost 21",
    stock: "in stock",
    brand: "Adidas",
    ratings: 4.9,
    reviews: 1800,
    original_price: 13999,
    discount_price: 11999,
    description: "Adidas Ultraboost 21 running shoes with enhanced comfort and energy return.",
    images: [
      { img: "https://m.media-amazon.com/images/I/51Er5-doMvL._SY695_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71oiQ5L6PUL._SX695_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71RcLjhS0cL._SX675_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71w8-iQ0lTL._SX675_.jpg" },
    ],
    best_seller: true,
    new_product: false,
  },
  {
    id: "i0j1k2l3-m4n5-6o7p-q8r9-s0t1u2v3w4x5",
    category: "Fashion",
    name: "Levi's 501 Original Jeans",
    stock: "in stock",
    brand: "Levi's",
    ratings: 4.6,
    reviews: 2000,
    original_price: 4999,
    discount_price: 3999,
    description: "Levi's 501 Original Jeans with a classic fit and durable fabric.",
    images: [
      { img: "https://m.media-amazon.com/images/I/616xchp1ECL._SY741_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61gzKcW79nL._SY741_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81AcZkW7qvL._SY741_.jpg" },
      { img: "https://m.media-amazon.com/images/I/718y-NIiTgL._SX679_.jpg" },
    ],
    best_seller: false,
    new_product: true,
  },

  // Books Category
  {
    id: "j1k2l3m4-n5o6-7p8q-r9s0-t1u2v3w4x5y6",
    category: "Books",
    name: "The Midnight Library by Matt Haig",
    stock: "in stock",
    brand: "Matt Haig",
    ratings: 4.8,
    reviews: 1400,
    original_price: 499,
    discount_price: 399,
    description: "The Midnight Library is a novel about regrets, choices, and second chances.",
    images: [
      { img: "https://m.media-amazon.com/images/I/71IdWKrhcrL._SL1500_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81Ps7z+yf0L._SL1500_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71SbVzONtTL._SL1500_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61wzFs2AEGL._SL1500_.jpg" },
    ],
    best_seller: true,
    new_product: false,
  },
  {
    id: "k2l3m4n5-o6p7-8q9r-s0t1-u2v3w4x5y6z7",
    category: "Books",
    name: "Atomic Habits by James Clear",
    stock: "in stock",
    brand: "James Clear",
    ratings: 4.9,
    reviews: 2200,
    original_price: 599,
    discount_price: 499,
    description: "Atomic Habits provides a framework for improving habits and achieving goals.",
    images: [
      { img: "https://m.media-amazon.com/images/I/61Bhf8CdaML._SY425_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71YZwR-ykEL._SY425_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81+9Gbu0isL._SY425_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61M6KzUbf7L._SY425_.jpg" },
    ],
    best_seller: true,
    new_product: true,
  },
  {
    id: "l3m4n5o6-p7q8-9r0s-t1u2-v3w4x5y6z7a8",
    category: "Books",
    name: "Where the Crawdads Sing by Delia Owens",
    stock: "in stock",
    brand: "Delia Owens",
    ratings: 4.7,
    reviews: 1700,
    original_price: 499,
    discount_price: 399,
    description: "Where the Crawdads Sing is a gripping mystery and coming-of-age novel.",
    images: [
      { img: "https://m.media-amazon.com/images/I/71g7zuSWppL._SY425_.jpg" },
      { img: "https://m.media-amazon.com/images/I/51AmdIUUxcL._SX342_SY445_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71LQV6-HZOL._SY425_.jpg" },
      { img: "https://m.media-amazon.com/images/I/715-ofxVvcL._SY425_.jpg" },
    ],
    best_seller: false,
    new_product: true,
  },
  // Sports Category
  {
    id: "m1n2o3p4-q5r6-7s8t-u9v0-w1x2y3z4a5b6",
    category: "Sports",
    name: "Adidas Soccer Ball",
    stock: "in stock",
    brand: "Adidas",
    ratings: 4.7,
    reviews: 850,
    original_price: 2499,
    discount_price: 1999,
    description: "Adidas soccer ball with high durability and precision for better game performance.",
    images: [
      { img: "https://m.media-amazon.com/images/I/61-pVFPSXqL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81f5wgkP1WL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61MEDDdDnSL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61dFezqEgzL._SX679_.jpg" },
    ],
    best_seller: false,
    new_product: true,
  },
  
  // Toys Category
  {
    id: "n2o3p4q5-r6s7-8t9u-v0w1-x2y3z4a5b6c7",
    category: "Toys",
    name: "LEGO Technic Lamborghini Sián",
    stock: "in stock",
    brand: "LEGO",
    ratings: 4.9,
    reviews: 600,
    original_price: 15999,
    discount_price: 13999,
    description: "LEGO Technic Lamborghini Sián model kit with detailed design and functional features.",
    images: [
      { img: "https://m.media-amazon.com/images/I/91jihK2pTJL._SY450_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81v1w9hyyoL._SX450_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81PliGgKQwL._SX450_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71Mgs-wLgxL._SY450_.jpg" },
    ],
    best_seller: true,
    new_product: false,
  },

  // Kitchenware Category
  {
    id: "o3p4q5r6-s7t8-9u0v-w1x2-y3z4a5b6c7d8",
    category: "Kitchenware",
    name: "Tefal Non-Stick Frying Pan",
    stock: "in stock",
    brand: "Tefal",
    ratings: 4.6,
    reviews: 700,
    original_price: 2999,
    discount_price: 2499,
    description: "Tefal non-stick frying pan with Thermo-Spot technology for perfect cooking results.",
    images: [
      { img: "https://m.media-amazon.com/images/I/51QbcwT+fCL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/6149kRjkQpL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61XJYZmRprL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/61ZzCTcLHWL._SX679_.jpg" },
    ],
    best_seller: false,
    new_product: true,
  },
  
  // Personal Care Category
  {
    id: "p4q5r6s7-t8u9-v0w1-x2y3-z4a5b6c7d8e9",
    category: "Personal Care",
    name: "Philips Sonicare Electric Toothbrush",
    stock: "in stock",
    brand: "Philips",
    ratings: 4.9,
    reviews: 1300,
    original_price: 8999,
    discount_price: 7499,
    description: "Philips Sonicare electric toothbrush with Sonic technology for superior cleaning.",
    images: [
      { img: "https://m.media-amazon.com/images/I/61e-yIP-+yL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/71KuZpzYLXL._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81+z28BMS-L._SX679_.jpg" },
      { img: "https://m.media-amazon.com/images/I/81GTMhYsO+L._SX679_.jpg" },
    ],
    best_seller: true,
    new_product: false,
  },
  ];
  
  